"""Add Employee table

Revision ID: 43409adfd50a
Revises: 7129e35b3a85
Create Date: 2025-09-12 09:14:04.217845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43409adfd50a'
down_revision = '7129e35b3a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio_number', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=120), nullable=False),
    sa.Column('office', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bio_number')
    )
    with op.batch_alter_table('leave_date_ranges', schema=None) as batch_op:
        batch_op.drop_index('ix_leave_date_ranges_leave_request_id_start_end')
        batch_op.create_index(batch_op.f('ix_leave_date_ranges_leave_request_id'), ['leave_request_id'], unique=False)

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index('idx_leave_barcode')
        batch_op.create_index(batch_op.f('ix_leave_requests_barcode'), ['barcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_barcode'))
        batch_op.create_index('idx_leave_barcode', ['barcode'], unique=False)

    with op.batch_alter_table('leave_date_ranges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_date_ranges_leave_request_id'))
        batch_op.create_index('ix_leave_date_ranges_leave_request_id_start_end', ['leave_request_id', 'start_date', 'end_date'], unique=False)

    op.drop_table('employees')
    # ### end Alembic commands ###
