"""add family background to employees

Revision ID: 4b7e2a92e906
Revises: 7727ae9b89e0
Create Date: 2025-10-13 16:53:30.340147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7e2a92e906'
down_revision = '7727ae9b89e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spouse_surname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('spouse_first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('spouse_middle_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('spouse_occupation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('spouse_employer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('spouse_business_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('spouse_telephone_no', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('father_surname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('father_first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('father_middle_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('father_extension', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mother_maiden_surname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('mother_maiden_first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('mother_maiden_middle_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('children_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('children_info')
        batch_op.drop_column('mother_maiden_middle_name')
        batch_op.drop_column('mother_maiden_first_name')
        batch_op.drop_column('mother_maiden_surname')
        batch_op.drop_column('father_extension')
        batch_op.drop_column('father_middle_name')
        batch_op.drop_column('father_first_name')
        batch_op.drop_column('father_surname')
        batch_op.drop_column('spouse_telephone_no')
        batch_op.drop_column('spouse_business_address')
        batch_op.drop_column('spouse_employer_name')
        batch_op.drop_column('spouse_occupation')
        batch_op.drop_column('spouse_middle_name')
        batch_op.drop_column('spouse_first_name')
        batch_op.drop_column('spouse_surname')

    # ### end Alembic commands ###
