"""add_document_performance_indexes

Revision ID: 9cc1ff94cc9f
Revises: 5e7a9c3d2b10
Create Date: 2025-10-01 11:29:56.627490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc1ff94cc9f'
down_revision = '5e7a9c3d2b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Wrap the document index creation in a try/except to avoid duplicate index errors during batch flush
    try:
        with op.batch_alter_table('document', schema=None) as batch_op:
            batch_op.create_index('ix_doc_barcode', ['barcode'], unique=False)
            batch_op.create_index('ix_doc_classification', ['classification'], unique=False)
            batch_op.create_index('ix_doc_creator_status', ['creator_id', 'status'], unique=False)
            batch_op.create_index('ix_doc_recipient_status', ['recipient_id', 'status'], unique=False)
            batch_op.create_index('ix_doc_timestamp', ['timestamp'], unique=False)
    except Exception:
        # Indexes may already exist; ignore to keep migration idempotent across environments
        pass

    with op.batch_alter_table('leave_date_ranges', schema=None) as batch_op:
        # Create single-column index first to satisfy FK requirements, then drop the old composite index
        batch_op.create_index(batch_op.f('ix_leave_date_ranges_leave_request_id'), ['leave_request_id'], unique=False)
        try:
            batch_op.drop_index('ix_leave_date_ranges_leave_request_id_start_end')
        except Exception:
            # If the index is auto-created for FK or already removed, ignore drop errors
            pass

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        try:
            batch_op.drop_index('idx_leave_barcode')
        except Exception:
            pass
        batch_op.create_index(batch_op.f('ix_leave_requests_barcode'), ['barcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        try:
            batch_op.drop_index(batch_op.f('ix_leave_requests_barcode'))
        except Exception:
            pass
        batch_op.create_index('idx_leave_barcode', ['barcode'], unique=False)

    with op.batch_alter_table('leave_date_ranges', schema=None) as batch_op:
        # Recreate composite index first, then drop the single-column index
        batch_op.create_index('ix_leave_date_ranges_leave_request_id_start_end', ['leave_request_id', 'start_date', 'end_date'], unique=False)
        try:
            batch_op.drop_index(batch_op.f('ix_leave_date_ranges_leave_request_id'))
        except Exception:
            pass

    # Wrap dropping of document indexes in a try/except to avoid failures if indexes don't exist
    try:
        with op.batch_alter_table('document', schema=None) as batch_op:
            batch_op.drop_index('ix_doc_timestamp')
            batch_op.drop_index('ix_doc_recipient_status')
            batch_op.drop_index('ix_doc_creator_status')
            batch_op.drop_index('ix_doc_classification')
            batch_op.drop_index('ix_doc_barcode')
    except Exception:
        pass

    # ### end Alembic commands ###
