"""add education records json

Revision ID: b1f9071a56a7
Revises: f739905f16ac
Create Date: 2025-10-14 13:36:10.048475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f9071a56a7'
down_revision = 'f739905f16ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elem_records_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sec_records_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('voc_records_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('college_records_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('grad_records_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('grad_records_json')
        batch_op.drop_column('college_records_json')
        batch_op.drop_column('voc_records_json')
        batch_op.drop_column('sec_records_json')
        batch_op.drop_column('elem_records_json')

    # ### end Alembic commands ###
