"""add educational background to employees

Revision ID: f739905f16ac
Revises: 4b7e2a92e906
Create Date: 2025-10-14 09:19:38.498299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f739905f16ac'
down_revision = '4b7e2a92e906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elem_school_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('elem_basic_education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('elem_period_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('elem_period_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('elem_highest_level', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('elem_year_graduated', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('elem_scholarships', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sec_school_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sec_basic_education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sec_period_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sec_period_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sec_highest_level', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sec_year_graduated', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('sec_scholarships', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('voc_school_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('voc_basic_education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('voc_period_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('voc_period_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('voc_highest_level', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('voc_year_graduated', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('voc_scholarships', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('college_school_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('college_basic_education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('college_period_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_period_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('college_highest_level', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('college_year_graduated', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('college_scholarships', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grad_school_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grad_basic_education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grad_period_from', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grad_period_to', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('grad_highest_level', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grad_year_graduated', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('grad_scholarships', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('grad_scholarships')
        batch_op.drop_column('grad_year_graduated')
        batch_op.drop_column('grad_highest_level')
        batch_op.drop_column('grad_period_to')
        batch_op.drop_column('grad_period_from')
        batch_op.drop_column('grad_basic_education')
        batch_op.drop_column('grad_school_name')
        batch_op.drop_column('college_scholarships')
        batch_op.drop_column('college_year_graduated')
        batch_op.drop_column('college_highest_level')
        batch_op.drop_column('college_period_to')
        batch_op.drop_column('college_period_from')
        batch_op.drop_column('college_basic_education')
        batch_op.drop_column('college_school_name')
        batch_op.drop_column('voc_scholarships')
        batch_op.drop_column('voc_year_graduated')
        batch_op.drop_column('voc_highest_level')
        batch_op.drop_column('voc_period_to')
        batch_op.drop_column('voc_period_from')
        batch_op.drop_column('voc_basic_education')
        batch_op.drop_column('voc_school_name')
        batch_op.drop_column('sec_scholarships')
        batch_op.drop_column('sec_year_graduated')
        batch_op.drop_column('sec_highest_level')
        batch_op.drop_column('sec_period_to')
        batch_op.drop_column('sec_period_from')
        batch_op.drop_column('sec_basic_education')
        batch_op.drop_column('sec_school_name')
        batch_op.drop_column('elem_scholarships')
        batch_op.drop_column('elem_year_graduated')
        batch_op.drop_column('elem_highest_level')
        batch_op.drop_column('elem_period_to')
        batch_op.drop_column('elem_period_from')
        batch_op.drop_column('elem_basic_education')
        batch_op.drop_column('elem_school_name')

    # ### end Alembic commands ###
