"""add date_posted to rsp_records

Revision ID: fa7ce5252904
Revises: 7c1d4a9e2b35
Create Date: 2026-02-11 15:02:36.583164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa7ce5252904'
down_revision = '7c1d4a9e2b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsp_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsp_records', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###
